### ISSUE TITLE
Using your Muesli code for large scale training efforts.

### ISSUE THREAD

**Issue by con-bren** [Itomigna2/Muesli-lunarlander#2]
Hello, my name is Connor. I'm a post doctoral researcher working at MILA. We looking for a codebase for Muesli to use in our video pretraining project (a joint venture between MILA and the Farama organization). The project's aim is to use internet-scale data to pretrain on video-action pairs in order to develop a foundation model to assist with downstream RL tasks.

Would you be available to discuss potential collaborations on this project? In particular, we are hoping that you could assist us with getting the code set up for our particular use cases.

**Comment by Itomigna2** [comment]
@con-bren 
Hi, Connor. Thank you for your interest. 
Can you send me an email to emtgit2@gmail.com?

Thank you.
